database:
  user: marketbill
  password: marketbill1234!
  net: tcp
  host: marketbill-db.ciegftzvpg1l.ap-northeast-2.rds.amazonaws.com
  port: 5432
  dbname: postgres

server:
  port: 8080

api:
  key: 4DC6A10B4F5D43D5977F364FC0DFE81C